SELECT 
A.ID, A.YEAR, A.PARAMETER_CODE, A.PIC_ID, 
B.PARAMETER_NAME, B.PARAMETER_CODE 
FROM classes A
LEFT JOIN gl_parameter B ON B.PARAMETER_CODE = A.PARAMETER_CODE
WHERE PARAMETER_PARENT_CODE = '1002'



SELECT 
PARAMETER_NAME, PARAMETER_CODE 
FROM gl_parameter 
WHERE PARAMETER_PARENT_CODE = '1002'